/*	File code.c: 2.2 (84/08/31,10:05:13) */
/*% cc -O -c %
 *
 */

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>

#include "defs.h"
#include "data.h"
#include "code.h"
#include "error.h"
#include "function.h"
#include "io.h"
#include "main.h"
#include "optimize.h"

/* locals */
int segment;

/* externs */
extern int arg_stack_flag;

/* convert comparison operation to a string */
const char * compare2str [] = {
	"equ",	// CMP_EQU
	"neq",	// CMP_NEQ
	"slt",	// CMP_SLT
	"sle",	// CMP_SLE
	"sgt",	// CMP_SGT
	"sge",	// CMP_SGE
	"ult",	// CMP_ULT
	"ule",	// CMP_ULE
	"ugt",	// CMP_UGT
	"uge"	// CMP_UGE
};

/*
 *	print all assembler info before any code is generated
 *
 */
void gdata (void)
{
	if (segment == 1) {
		segment = 0;
		ol(".bss");
	}
}

void gtext (void)
{
	if (segment == 0) {
		segment = 1;
		ol(".code");
	}
}

void header (void)
{
	time_t today;

	outstr("; Small-C HuC6280 (1997-Nov-08)\n");
	outstr("; became HuC      (2000-Feb-22)\n");
	outstr("; became HuCC     (2024-May-01)\n");
	outstr(";\n");
	outstr("; This file generated by ");
	outstr(HUC_VERSION);
	outstr("\n");
	outstr("; on ");
	time(&today);
	outstr(ctime(&today));
	outstr(";\n");
	outstr("\n");
	outstr("HUC\t\t=\t1\n");
	outstr("HUCC\t\t=\t1\n");
	/* Reserve space for further global definitions. */
	output_globdef = ftell(output);
	outstr("                                                                           ");
	nl();
}

void asmdefines (void)
{
	outstr(asmdefs);
}

void inc_startup (void)
{
	if (startup_incl == 0) {
		startup_incl = 1;

		nl();
		outstr("\t\tinclude\t\"hucc.asm\"\n");
		outstr("\t\t.data\n");
		outstr("\t\t.bank\tDATA_BANK\n\n");
		gtext();
		nl();
	}
}

/*
 *	print pseudo-op  to define a byte
 *
 */
void defbyte (void)
{
	ot(".db\t\t");
}

/*
 *	print pseudo-op to define storage
 *
 */
void defstorage (void)
{
	ot(".ds\t\t");
}

/*
 *	print pseudo-op to define a word
 *
 */
void defword (void)
{
	ot(".dw\t\t");
}

/*
 *	output instructions
 *
 */
void out_ins (int code, int type, intptr_t data)
{
	INS tmp;

	memset(&tmp, 0, sizeof(INS));

	tmp.ins_code = code;
	tmp.ins_type = type;
	tmp.ins_data = data;
	gen_ins(&tmp);
}

void out_ins_ex (int code, int type, intptr_t data, int imm_type, intptr_t imm_data)
{
	INS tmp;

	memset(&tmp, 0, sizeof(INS));

	tmp.ins_code = code;
	tmp.ins_type = type;
	tmp.ins_data = data;
	tmp.imm_type = imm_type;
	tmp.imm_data = imm_data;
	gen_ins(&tmp);
}

void out_ins_ex_arg (int code, int type, intptr_t data, int imm_type, intptr_t imm_data, char * string)
{
	INS tmp;

	memset(&tmp, 0, sizeof(INS));

	tmp.ins_code = code;
	tmp.ins_type = type;
	tmp.ins_data = data;
	tmp.imm_type = imm_type;
	tmp.imm_data = imm_data;
	tmp.arg[0] = string;
	gen_ins(&tmp);
}

void out_ins_sym (int code, int type, intptr_t data, SYMBOL *sym)
{
	INS tmp;

	memset(&tmp, 0, sizeof(INS));

	tmp.ins_code = code;
	tmp.ins_type = type;
	tmp.ins_data = data;
	tmp.sym = sym;
	gen_ins(&tmp);
}

void out_ins_cmp (int code, int type)
{
	INS tmp;

	memset(&tmp, 0, sizeof(INS));

	tmp.ins_code = code;
	tmp.cmp_type = type;
	gen_ins(&tmp);
}

void gen_ins (INS *tmp)
{
	static unsigned sequence = 0;
	tmp->sequence = sequence++;

	if (optimize)
		push_ins(tmp);
	else {
		if (arg_stack_flag)
			arg_push_ins(tmp);
		else
			gen_code(tmp);
	}
}

static void out_type (int type, intptr_t data)
{
	switch (type) {
	case T_VALUE:
		outdec((int)data);
		break;
	case T_LABEL:
		outlabel((int)data);
		break;
	case T_SYMBOL:
		outsymbol((SYMBOL *)data);
		break;
	case T_LITERAL:
		outstr((const char *)data);
		break;
	case T_STRING:
		outconst(litlab);
		outbyte('+');
		outdec((int)data);
		break;
	case T_BANK:
		outstr("BANK(");
		outstr((const char *)data);
		outstr(")");
		break;
	case T_VRAM:
		outstr("VRAM(");
		outstr((const char *)data);
		outstr(")");
		break;
	case T_PAL:
		outstr("PAL(");
		outstr((const char *)data);
		outstr(")");
		break;
	}
}

static void out_addr (int type, intptr_t data)
{
	switch (type) {
	case T_LABEL:
		outlabel((int)data);
		break;
	case T_SYMBOL:
		outsymbol((SYMBOL *)data);
		break;
	case T_LITERAL:
		outstr((const char *)data);
		break;
	case T_PTR:
		outstr("__ptr");
		break;
	case T_VALUE:
		outdec((int)data);
		break;
	case T_STACK:
		outstr("__stack");
		break;
	}
}

void dump_ins (INS *tmp)
{
	INS copy = *tmp;
	FILE *save = output;

	if (copy.ins_code == I_INFO)
		copy.ins_data = 0;

	output = stdout;
	gen_code(&copy);
	output = save;
}

/*
 *	gen assembly code
 *
 */
void gen_code (INS *tmp)
{
	enum ICODE code;
	int type;
	intptr_t data;
	int imm_type;
	intptr_t imm_data;

	code = tmp->ins_code;
	type = tmp->ins_type;
	data = tmp->ins_data;
	imm_type = tmp->imm_type;
	imm_data = tmp->imm_data;

	if (type == T_NOP)
		return;

	switch (code) {

	/* i-code for internal compiler information */

	case I_INFO:
		switch(type) {
		case T_SOURCE_LINE:
			if (data) {
				char * source = (char *)data;
				if (source)
					while (source[0] == ' ' || source[0] == '\t')
						++source;
				nl();
				ot(".dbg\tline,\t\"");
				if (tmp->arg[0]) {
					outstr(tmp->arg[0]);
				}
				outstr("\", ");
				outdec((int)imm_data);
				outstr("; ");
				if (source) {
					outstr(source);
					free((void *)data);
					tmp->ins_data = 0;
				}
				nl();
			}
			break;
		case T_CLEAR_LINE:
			nl();
			ol(".dbg\tclear");
			break;
#if 1
		case T_EXPRESSION:
			ol("; EXPRESSION");
			break;
#endif
		}
		break;

	/* i-code that retires the primary register contents */

	case I_FENCE:
		ot("__fence");
		nl();
		break;

	/* i-code that declares a byte sized primary register */

	case I_SHORT:
		ot("__short");
		nl();
		break;

	/* i-codes for handling farptr */

	case I_FARPTR:
		ot("__farptr\t");

		switch (type) {
		case T_LABEL:
			outlabel((int)data);
			break;
		case T_SYMBOL:
			outsymbol((SYMBOL *)data);
			break;
		case T_STRING:
			outconst(litlab);
			outbyte('+');
			outdec((int)data);
			break;
		}
		outstr(", ");
		outstr(tmp->arg[0]);
		outstr(", ");
		outstr(tmp->arg[1]);
		nl();
		break;

	case I_FARPTR_I:
		ot("__farptr_i\t");
		outsymbol((SYMBOL *)data);
		outstr(", ");
		outstr(tmp->arg[0]);
		outstr(", ");
		outstr(tmp->arg[1]);
		nl();
		break;

	case I_FARPTR_GET:
		ot("__farptr_get\t");
		outstr(tmp->arg[0]);
		outstr(", ");
		outstr(tmp->arg[1]);
		nl();
		break;

	case I_FGETW:
		ot("__farptr_i\t");
		outsymbol((SYMBOL *)data);
		nl();
		ol("  jsr\t_farpeekw.fast");
		break;

	case I_FGETB:
		ot("__farptr_i\t");
		outsymbol((SYMBOL *)data);
		nl();
		ol("__fgetb");
		break;

	case I_FGETUB:
		ot("__farptr_i\t");
		outsymbol((SYMBOL *)data);
		nl();
		ol("__fgetub");
		break;

	/* i-codes for interrupts */

	case I_SEI:
		ol("sei");
		break;

	case I_CLI:
		ol("cli");
		break;

	/* i-codes for calling functions */

	case I_MACRO:
		/* because functions don't need to be pre-declared
		   in HuC we get a string and not a symbol */
		switch (type) {
		case T_LITERAL:
			ot(" ");
			prefix();
			outstr((const char *)data);
			if (imm_data) {
				outstr(".");
				outdec((int)imm_data);
			}
			break;
		}
		nl();
		break;

	case I_CALL:
		/* because functions don't need to be pre-declared
		   in HuC we get a string and not a symbol */
		switch (type) {
		case T_LITERAL:
			ot("__call\t\t");
			prefix();
			outstr((const char *)data);
			if (imm_data) {
				outstr(".");
				outdec((int)imm_data);
			}
			break;
		}
		nl();
		break;

	case I_FUNCP_WR:
		ol("__funcp.wr");
		break;

	case I_CALLP:
		ol("__callp");
		break;

	/* i-codes for C functions and the C parameter stack */

	case I_ENTER:
		ot("__enter\t\t");
		outsymbol((SYMBOL *)data);
		nl();
		break;

	case I_RETURN:
		ot("__return\t");
		outdec((int)data);
		nl();
		break;

	case I_MODSP:
		ot("__modsp");
		if (type == T_LITERAL) {
			outstr("_goto\t");
			outstr((const char *)data);
		}
		else {
			outstr("\t\t");
			outdec((int)data);
		}
		nl();
		break;

	case I_PUSHARG_WR:
		ol("__pusharg.wr");
		break;

	case I_PUSH_WR:
		ol("__push.wr");
		break;

	case I_POP_WR:
		ol("__pop.wr");
		break;

	case I_SPUSH_WR:
		ol("__spush.wr");
		break;

	case I_SPOP_WR:
		ol("__spop.wr");
		break;

	case I_SPUSH_UR:
		ol("__spush.ur");
		break;

	case I_SPOP_UR:
		ol("__spop.ur");
		break;

	/* i-codes for handling boolean tests and branching */

	case I_SWITCH_WR:
		ot("__switch.wr\t");
		outlabel((int)data);
		nl();
		break;

	case I_SWITCH_UR:
		ot("__switch.ur\t");
		outlabel((int)data);
		nl();
		break;

	case I_DEFAULT:
		ol("__default");
		break;

	case I_CASE:
		ot("__case\t\t");
		if (type == T_VALUE)
			outdec((int)data);
		nl();
		break;

	case I_ENDCASE:
		ol("__endcase");
		break;

	case I_LABEL:
		outlabel((int)data);
		col();
		break;

	case I_ALIAS:
		outlabel((int)data);
		ot(".alias\t\t");
		outlabel((int)imm_data);
		nl();
		break;

	case I_BRA:
		ot("__bra\t\t");
		outlabel((int)data);
		nl();
		break;

	case I_BFALSE:
		ot("__bfalse\t");
		outlabel((int)data);
		nl();
		break;

	case I_BTRUE:
		ot("__btrue\t\t");
		outlabel((int)data);
		nl();
		break;

	case I_DEF:
		outstr((const char *)data);
		outstr("\t=\t");
		outdec((int)imm_data);
		nl();
		break;

	case I_CMP_WT:
		ot("__");
		outstr(compare2str[tmp->cmp_type]);
		outstr("_w.wt");
		nl();
		break;

	case X_CMP_WI:
		ot("__");
		outstr(compare2str[tmp->cmp_type]);
		outstr("_w.wi\t");
		out_type(type, data);
		nl();
		break;

	case X_CMP_WM:
		ot("__");
		outstr(compare2str[tmp->cmp_type]);
		outstr("_w.wm\t");
		out_type(type, data);
		nl();
		break;

	case X_CMP_UM:
		ot("__");
		outstr(compare2str[tmp->cmp_type]);
		outstr("_w.um\t");
		out_type(type, data);
		nl();
		break;

	case X_CMP_WS:
		ot("__");
		outstr(compare2str[tmp->cmp_type]);
		outstr("_w.ws\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_CMP_US:
		ot("__");
		outstr(compare2str[tmp->cmp_type]);
		outstr("_w.us\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_CMP_WAX:
		ot("__");
		outstr(compare2str[tmp->cmp_type]);
		outstr("_w.wax\t");
		out_type(type, data);
		nl();
		break;

	case X_CMP_UAX:
		ot("__");
		outstr(compare2str[tmp->cmp_type]);
		outstr("_w.uax\t");
		out_type(type, data);
		nl();
		break;

	case X_CMP_UIQ:
		ot("__");
		outstr(compare2str[tmp->cmp_type]);
		outstr("_b.uiq\t");
		out_type(type, data);
		nl();
		break;

	case X_CMP_UMQ:
		ot("__");
		outstr(compare2str[tmp->cmp_type]);
		outstr("_b.umq\t");
		out_type(type, data);
		nl();
		break;

	case X_CMP_USQ:
		ot("__");
		outstr(compare2str[tmp->cmp_type]);
		outstr("_b.usq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_CMP_UAXQ:
		ot("__");
		outstr(compare2str[tmp->cmp_type]);
		outstr("_b.uaxq\t");
		out_type(type, data);
		nl();
		break;

	case I_NOT_WR:
		ol("__not.wr");
		break;

	case X_NOT_WP:
		ot("__not.wp\t");
		out_addr(type, data);
		nl();
		break;

	case X_NOT_WM:
		ot("__not.wm\t");
		out_addr(type, data);
		nl();
		break;

	case X_NOT_WS:
		ot("__not.ws\t");
		outdec((int)data);
		nl();
		break;

	case X_NOT_WAR:
		ot("__not.war\t");
		out_addr(type, data);
		nl();
		break;

	case X_NOT_WAX:
		ot("__not.wax\t");
		out_addr(type, data);
		nl();
		break;

	case X_NOT_UP:
		ot("__not.up\t");
		out_addr(type, data);
		nl();
		break;

	case X_NOT_UM:
		ot("__not.um\t");
		out_addr(type, data);
		nl();
		break;

	case X_NOT_US:
		ot("__not.us\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_NOT_UAR:
		ot("__not.uar\t");
		out_addr(type, data);
		nl();
		break;

	case X_NOT_UAX:
		ot("__not.uax\t");
		out_addr(type, data);
		nl();
		break;

	case X_NOT_UAY:
		ot("__not.uay\t");
		out_addr(type, data);
		nl();
		break;

	case I_TST_WR:
		ol("__tst.wr");
		break;

	case X_TST_WP:
		ot("__tst.wp\t");
		out_addr(type, data);
		nl();
		break;

	case X_TST_WM:
		ot("__tst.wm\t");
		out_addr(type, data);
		nl();
		break;

	case X_TST_WS:
		ot("__tst.ws\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_TST_WAR:
		ot("__tst.war\t");
		out_addr(type, data);
		nl();
		break;

	case X_TST_WAX:
		ot("__tst.wax\t");
		out_addr(type, data);
		nl();
		break;

	case X_TST_UP:
		ot("__tst.up\t");
		out_addr(type, data);
		nl();
		break;

	case X_TST_UM:
		ot("__tst.um\t");
		out_addr(type, data);
		nl();
		break;

	case X_TST_US:
		ot("__tst.us\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_TST_UAR:
		ot("__tst.uar\t");
		out_addr(type, data);
		nl();
		break;

	case X_TST_UAX:
		ot("__tst.uax\t");
		out_addr(type, data);
		nl();
		break;

	case X_TST_UAY:
		ot("__tst.uay\t");
		out_addr(type, data);
		nl();
		break;

	case X_NAND_WI:
		ot("__nand.wi\t");
		out_type(type, data);
		nl();
		break;

	case X_TAND_WI:
		ot("__tand.wi\t");
		out_type(type, data);
		nl();
		break;

	case X_NOT_CF:
		ol("__not.cf");
		break;

	case I_BOOLEAN:
		ol("__bool");
		break;

	case X_BOOLNOT_WR:
		ol("__boolnot.wr");
		break;

	case X_BOOLNOT_WP:
		ot("__boolnot.wp\t");
		out_addr(type, data);
		nl();
		break;

	case X_BOOLNOT_WM:
		ot("__boolnot.wm\t");
		out_addr(type, data);
		nl();
		break;

	case X_BOOLNOT_WS:
		ot("__boolnot.ws\t");
		outdec((int)data);
		nl();
		break;

	case X_BOOLNOT_WAR:
		ot("__boolnot.war\t");
		out_addr(type, data);
		nl();
		break;

	case X_BOOLNOT_WAX:
		ot("__boolnot.wax\t");
		out_addr(type, data);
		nl();
		break;

	case X_BOOLNOT_UP:
		ot("__boolnot.up\t");
		out_addr(type, data);
		nl();
		break;

	case X_BOOLNOT_UM:
		ot("__boolnot.um\t");
		out_addr(type, data);
		nl();
		break;

	case X_BOOLNOT_US:
		ot("__boolnot.us\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_BOOLNOT_UAR:
		ot("__boolnot.uar\t");
		out_addr(type, data);
		nl();
		break;

	case X_BOOLNOT_UAX:
		ot("__boolnot.uax\t");
		out_addr(type, data);
		nl();
		break;

	case X_BOOLNOT_UAY:
		ot("__boolnot.uay\t");
		out_addr(type, data);
		nl();
		break;

	/* i-codes for loading the primary register */

	case I_LD_WI:
		ot("__ld.wi\t\t");
		out_type(type, data);
		nl();
		break;

	case X_LD_UIQ:
		ot("__ld.uiq\t");
		out_type(type, data);
		nl();
		break;

	case I_LEA_S:
		ot("__lea.s\t\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case I_LD_WM:
		ot("__ld.wm\t\t");
		out_addr(type, data);
		nl();
		break;

	case I_LD_BM:
		ot("__ld.bm\t\t");
		out_type(type, data);
		nl();
		break;

	case I_LD_UM:
		ot("__ld.um\t\t");
		out_type(type, data);
		nl();
		break;

	case X_LD_WMQ:
		ot("__ld.wmq\t");
		out_addr(type, data);
		nl();
		break;

	case X_LD_BMQ:
		ot("__ld.bmq\t");
		out_type(type, data);
		nl();
		break;

	case X_LD_UMQ:
		ot("__ld.umq\t");
		out_type(type, data);
		nl();
		break;

	case X_LDX_WMQ:
		ot("__ldx.wmq\t");
		out_addr(type, data);
		nl();
		break;

	case X_LDX_BMQ:
		ot("__ldx.bmq\t");
		out_type(type, data);
		nl();
		break;

	case X_LDX_UMQ:
		ot("__ldx.umq\t");
		out_type(type, data);
		nl();
		break;

	case X_LD2X_WMQ:
		ot("__ld2x.wmq\t");
		out_addr(type, data);
		nl();
		break;

	case X_LD2X_BMQ:
		ot("__ld2x.bmq\t");
		out_type(type, data);
		nl();
		break;

	case X_LD2X_UMQ:
		ot("__ld2x.umq\t");
		out_type(type, data);
		nl();
		break;

	case X_LD2X_WM:
		ot("__ld2x.wm\t");
		out_addr(type, data);
		nl();
		break;

	case X_LD2X_BM:
		ot("__ld2x.bm\t");
		out_type(type, data);
		nl();
		break;

	case X_LD2X_UM:
		ot("__ld2x.um\t");
		out_type(type, data);
		nl();
		break;

	case X_LDY_WMQ:
		ot("__ldy.wmq\t");
		out_addr(type, data);
		nl();
		break;

	case X_LDY_BMQ:
		ot("__ldy.bmq\t");
		out_type(type, data);
		nl();
		break;

	case X_LDY_UMQ:
		ot("__ldy.umq\t");
		out_type(type, data);
		nl();
		break;

	case I_LD_WP:
		ot("__ld.wp\t\t");
		out_addr(type, data);
		nl();
		break;

	case I_LD_BP:
		ot("__ld.bp\t\t");
		out_addr(type, data);
		nl();
		break;

	case I_LD_UP:
		ot("__ld.up\t\t");
		out_addr(type, data);
		nl();
		break;

	case X_LD_UPQ:
		ot("__ld.upq\t");
		out_addr(type, data);
		nl();
		break;

	case X_LD_WAR:
		ot("__ld.war\t");
		out_type(type, data);
		nl();
		break;

	case X_LD_BAR:
		ot("__ld.bar\t");
		out_type(type, data);
		nl();
		break;

	case X_LD_UAR:
		ot("__ld.uar\t");
		out_type(type, data);
		nl();
		break;

	case X_LD_UARQ:
		ot("__ld.uarq\t");
		out_type(type, data);
		nl();
		break;

	case X_LD_WAX:
		ot("__ld.wax\t");
		out_type(type, data);
		nl();
		break;

	case X_LD_BAX:
		ot("__ld.bax\t");
		out_type(type, data);
		nl();
		break;

	case X_LD_UAX:
		ot("__ld.uax\t");
		out_type(type, data);
		nl();
		break;

	case X_LD_UAXQ:
		ot("__ld.uaxq\t");
		out_type(type, data);
		nl();
		break;

	case X_LD_BAY:
		ot("__ld.bay\t");
		out_type(type, data);
		nl();
		break;

	case X_LD_UAY:
		ot("__ld.uay\t");
		out_type(type, data);
		nl();
		break;

	case X_LD_WS:
		ot("__ld.ws\t\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LD_BS:
		ot("__ld.bs\t\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LD_US:
		ot("__ld.us\t\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LD_WSQ:
		ot("__ld.wsq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LD_BSQ:
		ot("__ld.bsq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LD_USQ:
		ot("__ld.usq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LDX_WS:
		ot("__ldx.ws\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LDX_BS:
		ot("__ldx.bs\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LDX_US:
		ot("__ldx.us\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LDX_WSQ:
		ot("__ldx.wsq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LDX_BSQ:
		ot("__ldx.bsq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LDX_USQ:
		ot("__ldx.usq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LD2X_WS:
		ot("__ld2x.ws\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LD2X_BS:
		ot("__ld2x.bs\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LD2X_US:
		ot("__ld2x.us\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LD2X_WSQ:
		ot("__ld2x.wsq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LD2X_BSQ:
		ot("__ld2x.bsq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LD2X_USQ:
		ot("__ld2x.usq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LDY_WSQ:
		ot("__ldy.wsq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LDY_BSQ:
		ot("__ldy.bsq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LDY_USQ:
		ot("__ldy.usq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LDP_WAR:
		ot("__ldp.war\t");
		out_type(type, data);
		nl();
		break;

	case X_LDP_BAR:
		ot("__ldp.bar\t");
		out_type(type, data);
		nl();
		break;

	case X_LDP_UAR:
		ot("__ldp.uar\t");
		out_type(type, data);
		nl();
		break;

	case X_LDP_WAX:
		ot("__ldp.wax\t");
		out_type(type, data);
		nl();
		break;

	case X_LDP_BAX:
		ot("__ldp.bax\t");
		out_type(type, data);
		nl();
		break;

	case X_LDP_UAX:
		ot("__ldp.uax\t");
		out_type(type, data);
		nl();
		break;

	case X_LDP_BAY:
		ot("__ldp.bay\t");
		out_type(type, data);
		nl();
		break;

	case X_LDP_UAY:
		ot("__ldp.uay\t");
		out_type(type, data);
		nl();
		break;

	/* i-codes for pre- and post- increment and decrement */

	case X_INCLD_WM:
		ot("__incld.wm\t");
		out_type(type, data);
		nl();
		break;

	case X_LDINC_WM:
		ot("__ldinc.wm\t");
		out_type(type, data);
		nl();
		break;

	case X_DECLD_WM:
		ot("__decld.wm\t");
		out_type(type, data);
		nl();
		break;

	case X_LDDEC_WM:
		ot("__lddec.wm\t");
		out_type(type, data);
		nl();
		break;

	case X_INCLD_BM:
		ot("__incld.bm\t");
		out_type(type, data);
		nl();
		break;

	case X_LDINC_BM:
		ot("__ldinc.bm\t");
		out_type(type, data);
		nl();
		break;

	case X_DECLD_BM:
		ot("__decld.bm\t");
		out_type(type, data);
		nl();
		break;

	case X_LDDEC_BM:
		ot("__lddec.bm\t");
		out_type(type, data);
		nl();
		break;


	case X_INCLD_UM:
		ot("__incld.um\t");
		out_type(type, data);
		nl();
		break;

	case X_LDINC_UM:
		ot("__ldinc.um\t");
		out_type(type, data);
		nl();
		break;

	case X_DECLD_UM:
		ot("__decld.um\t");
		out_type(type, data);
		nl();
		break;

	case X_LDDEC_UM:
		ot("__lddec.um\t");
		out_type(type, data);
		nl();
		break;

	case X_INC_WMQ:
		ot("__inc.wmq\t");
		out_type(type, data);
		nl();
		break;

	case X_INC_UMQ:
		ot("__inc.umq\t");
		out_type(type, data);
		nl();
		break;

	case X_DEC_WMQ:
		ot("__dec.wmq\t");
		out_type(type, data);
		nl();
		break;

	case X_DEC_UMQ:
		ot("__dec.umq\t");
		out_type(type, data);
		nl();
		break;

	case X_INCLD_WS:
		ot("__incld.ws\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LDINC_WS:
		ot("__ldinc.ws\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_DECLD_WS:
		ot("__decld.ws\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LDDEC_WS:
		ot("__lddec.ws\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_INCLD_BS:
		ot("__incld.bs\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LDINC_BS:
		ot("__ldinc.bs\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_DECLD_BS:
		ot("__decld.bs\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LDDEC_BS:
		ot("__lddec.bs\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_INCLD_US:
		ot("__incld.us\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LDINC_US:
		ot("__ldinc.us\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_DECLD_US:
		ot("__decld.us\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_LDDEC_US:
		ot("__lddec.us\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_INC_WSQ:
		ot("__inc.wsq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_INC_USQ:
		ot("__inc.usq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_DEC_WSQ:
		ot("__dec.wsq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_DEC_USQ:
		ot("__dec.usq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_INCLD_WAR:
		ot("__incld.war\t");
		out_type(type, data);
		nl();
		break;

	case X_LDINC_WAR:
		ot("__ldinc.war\t");
		out_type(type, data);
		nl();
		break;

	case X_DECLD_WAR:
		ot("__decld.war\t");
		out_type(type, data);
		nl();
		break;

	case X_LDDEC_WAR:
		ot("__lddec.war\t");
		out_type(type, data);
		nl();
		break;

	case X_INCLD_BAR:
		ot("__incld.bar\t");
		out_type(type, data);
		nl();
		break;

	case X_LDINC_BAR:
		ot("__ldinc.bar\t");
		out_type(type, data);
		nl();
		break;

	case X_DECLD_BAR:
		ot("__decld.bar\t");
		out_type(type, data);
		nl();
		break;

	case X_LDDEC_BAR:
		ot("__lddec.bar\t");
		out_type(type, data);
		nl();
		break;

	case X_INCLD_UAR:
		ot("__incld.uar\t");
		out_type(type, data);
		nl();
		break;

	case X_LDINC_UAR:
		ot("__ldinc.uar\t");
		out_type(type, data);
		nl();
		break;

	case X_DECLD_UAR:
		ot("__decld.uar\t");
		out_type(type, data);
		nl();
		break;

	case X_LDDEC_UAR:
		ot("__lddec.uar\t");
		out_type(type, data);
		nl();
		break;

	case X_INC_WARQ:
		ot("__inc.warq\t");
		out_type(type, data);
		nl();
		break;

	case X_INC_UARQ:
		ot("__inc.uarq\t");
		out_type(type, data);
		nl();
		break;

	case X_DEC_WARQ:
		ot("__dec.warq\t");
		out_type(type, data);
		nl();
		break;

	case X_DEC_UARQ:
		ot("__dec.uarq\t");
		out_type(type, data);
		nl();
		break;

	case X_INCLD_WAX:
		ot("__incld.wax\t");
		out_type(type, data);
		nl();
		break;

	case X_LDINC_WAX:
		ot("__ldinc.wax\t");
		out_type(type, data);
		nl();
		break;

	case X_DECLD_WAX:
		ot("__decld.wax\t");
		out_type(type, data);
		nl();
		break;

	case X_LDDEC_WAX:
		ot("__lddec.wax\t");
		out_type(type, data);
		nl();
		break;

	case X_INCLD_BAX:
		ot("__incld.bax\t");
		out_type(type, data);
		nl();
		break;

	case X_LDINC_BAX:
		ot("__ldinc.bax\t");
		out_type(type, data);
		nl();
		break;

	case X_DECLD_BAX:
		ot("__decld.bax\t");
		out_type(type, data);
		nl();
		break;

	case X_LDDEC_BAX:
		ot("__lddec.bax\t");
		out_type(type, data);
		nl();
		break;

	case X_INCLD_UAX:
		ot("__incld.uax\t");
		out_type(type, data);
		nl();
		break;

	case X_LDINC_UAX:
		ot("__ldinc.uax\t");
		out_type(type, data);
		nl();
		break;

	case X_DECLD_UAX:
		ot("__decld.uax\t");
		out_type(type, data);
		nl();
		break;

	case X_LDDEC_UAX:
		ot("__lddec.uax\t");
		out_type(type, data);
		nl();
		break;

	case X_INC_WAXQ:
		ot("__inc.waxq\t");
		out_type(type, data);
		nl();
		break;

	case X_INC_UAXQ:
		ot("__inc.uaxq\t");
		out_type(type, data);
		nl();
		break;

	case X_DEC_WAXQ:
		ot("__dec.waxq\t");
		out_type(type, data);
		nl();
		break;

	case X_DEC_UAXQ:
		ot("__dec.uaxq\t");
		out_type(type, data);
		nl();
		break;

	case X_INCLD_BAY:
		ot("__incld.bay\t");
		out_type(type, data);
		nl();
		break;

	case X_LDINC_BAY:
		ot("__ldinc.bay\t");
		out_type(type, data);
		nl();
		break;

	case X_DECLD_BAY:
		ot("__decld.bay\t");
		out_type(type, data);
		nl();
		break;

	case X_LDDEC_BAY:
		ot("__lddec.bay\t");
		out_type(type, data);
		nl();
		break;

	case X_INCLD_UAY:
		ot("__incld.uay\t");
		out_type(type, data);
		nl();
		break;

	case X_LDINC_UAY:
		ot("__ldinc.uay\t");
		out_type(type, data);
		nl();
		break;

	case X_DECLD_UAY:
		ot("__decld.uay\t");
		out_type(type, data);
		nl();
		break;

	case X_LDDEC_UAY:
		ot("__lddec.uay\t");
		out_type(type, data);
		nl();
		break;

	case X_INC_UAYQ:
		ot("__inc.uayq\t");
		out_type(type, data);
		nl();
		break;

	case X_DEC_UAYQ:
		ot("__dec.uayq\t");
		out_type(type, data);
		nl();
		break;

	/* i-codes for saving the primary register */

	case I_ST_WPT:
		ol("__st.wpt");
		break;

	case I_ST_UPT:
		ol("__st.upt");
		break;

	case X_ST_WPTQ:
		ol("__st.wptq");
		break;

	case X_ST_UPTQ:
		ol("__st.uptq");
		break;

	case I_ST_WM:
		ot("__st.wm\t\t");
		out_addr(type, data);
		nl();
		break;

	case I_ST_UM:
		ot("__st.um\t\t");
		out_addr(type, data);
		nl();
		break;

	case X_ST_WMQ:
		ot("__st.wmq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ST_UMQ:
		ot("__st.umq\t");
		out_addr(type, data);
		nl();
		break;

	case I_ST_WMIQ:
		ot("__st.wmiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_type(type, data);
		nl();
		break;

	case I_ST_UMIQ:
		ot("__st.umiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_type(type, data);
		nl();
		break;

	case X_ST_WP:
		ot("__st.wp\t\t");
		out_addr(type, data);
		nl();
		break;

	case X_ST_UP:
		ot("__st.up\t\t");
		out_addr(type, data);
		nl();
		break;

	case X_ST_WPQ:
		ot("__st.wpq\t\t");
		out_addr(type, data);
		nl();
		break;

	case X_ST_UPQ:
		ot("__st.upq\t\t");
		out_addr(type, data);
		nl();
		break;

	case X_ST_WPI:
		ot("__st.wpi\t\t");
		outdec((int)data);
		nl();
		break;

	case X_ST_UPI:
		ot("__st.upi\t\t");
		outdec((int)data);
		nl();
		break;

	case X_ST_WS:
		ot("__st.ws\t\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_ST_US:
		ot("__st.us\t\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_ST_WSQ:
		ot("__st.wsq\t\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_ST_USQ:
		ot("__st.usq\t\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case I_ST_WSIQ:
		ot("__st.wsiq\t");
		outdec((int)imm_data);
		outstr(", ");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case I_ST_USIQ:
		ot("__st.usiq\t");
		outdec((int)imm_data);
		outstr(", ");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_INDEX_WR:
		ot("__index.wr\t");
		out_type(type, data);
		nl();
		break;

	case X_INDEX_UR:
		ot("__index.ur\t");
		out_type(type, data);
		nl();
		break;

	case X_ST_WAT:
		ot("__st.wat\t");
		out_type(type, data);
		nl();
		break;

	case X_ST_UAT:
		ot("__st.uat\t");
		out_type(type, data);
		nl();
		break;

	case X_ST_WATQ:
		ot("__st.watq\t");
		out_type(type, data);
		nl();
		break;

	case X_ST_UATQ:
		ot("__st.uatq\t");
		out_type(type, data);
		nl();
		break;

	case X_ST_WATIQ:
		ot("__st.watiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_type(type, data);
		nl();
		break;

	case X_ST_UATIQ:
		ot("__st.uatiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_type(type, data);
		nl();
		break;

	case X_ST_WAX:
		ot("__st.wax\t");
		out_type(type, data);
		nl();
		break;

	case X_ST_UAX:
		ot("__st.uax\t");
		out_type(type, data);
		nl();
		break;

	case X_ST_WAXQ:
		ot("__st.waxq\t");
		out_type(type, data);
		nl();
		break;

	case X_ST_UAXQ:
		ot("__st.uaxq\t");
		out_type(type, data);
		nl();
		break;

	case X_ST_WAXIQ:
		ot("__st.waxiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_type(type, data);
		nl();
		break;

	case X_ST_UAXIQ:
		ot("__st.uaxiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_type(type, data);
		nl();
		break;

	/* i-codes for extending a byte to a word */

	case I_EXT_BR:
		ol("__ext.br");
		break;

	case I_EXT_UR:
		ol("__ext.ur");
		break;

	/* i-codes for 16-bit math with the primary register */

	case I_COM_WR:
		ol("__com.wr");
		break;

	case I_NEG_WR:
		ol("__neg.wr");
		break;

	case I_ADD_WT:
		ol("__add.wt");
		break;

	case I_ADD_WI:
		ot("__add.wi\t");
		out_type(type, data);
		nl();
		break;

	case X_ADD_WM:
		ot("__add.wm\t");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_UM:
		ot("__add.um\t");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_WP:
		ot("__add.wp\t");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_UP:
		ot("__add.up\t");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_WS:
		ot("__add.ws\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_ADD_US:
		ot("__add.us\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_ADD_WAT:
		ot("__add.wat\t");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_UAT:
		ot("__add.uat\t");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_WAX:
		ot("__add.wax\t");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_UAX:
		ot("__add.uax\t");
		out_addr(type, data);
		nl();
		break;

	case I_SUB_WT:
		ol("__sub.wt");
		break;

	case I_SUB_WI:
		ot("__sub.wi\t");
		out_type(type, data);
		nl();
		break;

	case X_SUB_WM:
		ot("__sub.wm\t");
		out_addr(type, data);
		nl();
		break;

	case X_SUB_UM:
		ot("__sub.um\t");
		out_addr(type, data);
		nl();
		break;

	case X_SUB_WP:
		ot("__sub.wp\t");
		out_addr(type, data);
		nl();
		break;

	case X_SUB_UP:
		ot("__sub.up\t");
		out_addr(type, data);
		nl();
		break;

	case X_SUB_WS:
		ot("__sub.ws\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_SUB_US:
		ot("__sub.us\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_SUB_WAT:
		ot("__sub.wat\t");
		out_addr(type, data);
		nl();
		break;

	case X_SUB_UAT:
		ot("__sub.uat\t");
		out_addr(type, data);
		nl();
		break;

	case X_SUB_WAX:
		ot("__sub.wax\t");
		out_addr(type, data);
		nl();
		break;

	case X_SUB_UAX:
		ot("__sub.uax\t");
		out_addr(type, data);
		nl();
		break;

	case X_ISUB_WT:
		ol("__isub.wt");
		break;

	case X_ISUB_WI:
		ot("__isub.wi\t");
		out_type(type, data);
		nl();
		break;

	case X_ISUB_WM:
		ot("__isub.wm\t");
		out_addr(type, data);
		nl();
		break;

	case X_ISUB_UM:
		ot("__isub.um\t");
		out_addr(type, data);
		nl();
		break;

	case X_ISUB_WP:
		ot("__isub.wp\t");
		out_addr(type, data);
		nl();
		break;

	case X_ISUB_UP:
		ot("__isub.up\t");
		out_addr(type, data);
		nl();
		break;

	case X_ISUB_WS:
		ot("__isub.ws\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_ISUB_US:
		ot("__isub.us\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_ISUB_WAT:
		ot("__isub.wat\t");
		out_addr(type, data);
		nl();
		break;

	case X_ISUB_UAT:
		ot("__isub.uat\t");
		out_addr(type, data);
		nl();
		break;

	case X_ISUB_WAX:
		ot("__isub.wax\t");
		out_addr(type, data);
		nl();
		break;

	case X_ISUB_UAX:
		ot("__isub.uax\t");
		out_addr(type, data);
		nl();
		break;

	case I_AND_WT:
		ol("__and.wt");
		break;

	case X_AND_WI:
		ot("__and.wi\t");
		out_type(type, data);
		nl();
		break;

	case X_AND_WM:
		ot("__and.wm\t");
		out_addr(type, data);
		nl();
		break;

	case X_AND_UM:
		ot("__and.um\t");
		out_addr(type, data);
		nl();
		break;

	case X_AND_WP:
		ot("__and.wp\t");
		out_addr(type, data);
		nl();
		break;

	case X_AND_UP:
		ot("__and.up\t");
		out_addr(type, data);
		nl();
		break;

	case X_AND_WS:
		ot("__and.ws\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_AND_US:
		ot("__and.us\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_AND_WAT:
		ot("__and.wat\t");
		out_addr(type, data);
		nl();
		break;

	case X_AND_UAT:
		ot("__and.uat\t");
		out_addr(type, data);
		nl();
		break;

	case X_AND_WAX:
		ot("__and.wax\t");
		out_addr(type, data);
		nl();
		break;

	case X_AND_UAX:
		ot("__and.uax\t");
		out_addr(type, data);
		nl();
		break;

	case I_EOR_WT:
		ol("__eor.wt");
		break;

	case X_EOR_WI:
		ot("__eor.wi\t");
		out_type(type, data);
		nl();
		break;

	case X_EOR_WM:
		ot("__eor.wm\t");
		out_addr(type, data);
		nl();
		break;

	case X_EOR_UM:
		ot("__eor.um\t");
		out_addr(type, data);
		nl();
		break;

	case X_EOR_WP:
		ot("__eor.wp\t");
		out_addr(type, data);
		nl();
		break;

	case X_EOR_UP:
		ot("__eor.up\t");
		out_addr(type, data);
		nl();
		break;

	case X_EOR_WS:
		ot("__eor.ws\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_EOR_US:
		ot("__eor.us\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_EOR_WAT:
		ot("__eor.wat\t");
		out_addr(type, data);
		nl();
		break;

	case X_EOR_UAT:
		ot("__eor.uat\t");
		out_addr(type, data);
		nl();
		break;

	case X_EOR_WAX:
		ot("__eor.wax\t");
		out_addr(type, data);
		nl();
		break;

	case X_EOR_UAX:
		ot("__eor.uax\t");
		out_addr(type, data);
		nl();
		break;

	case I_OR_WT:
		ol("__or.wt");
		break;

	case X_OR_WI:
		ot("__or.wi\t\t");
		out_type(type, data);
		nl();
		break;

	case X_OR_WM:
		ot("__or.wm\t\t");
		out_addr(type, data);
		nl();
		break;

	case X_OR_UM:
		ot("__or.um\t\t");
		out_addr(type, data);
		nl();
		break;

	case X_OR_WP:
		ot("__or.wp\t\t");
		out_addr(type, data);
		nl();
		break;

	case X_OR_UP:
		ot("__or.up\t\t");
		out_addr(type, data);
		nl();
		break;

	case X_OR_WS:
		ot("__or.ws\t\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_OR_US:
		ot("__or.us\t\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_OR_WAT:
		ot("__or.wat\t");
		out_addr(type, data);
		nl();
		break;

	case X_OR_UAT:
		ot("__or.uat\t");
		out_addr(type, data);
		nl();
		break;

	case X_OR_WAX:
		ot("__or.wax\t");
		out_addr(type, data);
		nl();
		break;

	case X_OR_UAX:
		ot("__or.uax\t");
		out_addr(type, data);
		nl();
		break;

	case I_ASL_WT:
		ol("__asl.wt");
		break;

	case I_ASL_WI:
		ot("__asl.wi\t");
		out_type(type, data);
		nl();
		break;

	case I_ASL_WR:
		ol("__asl.wr");
		break;

	case I_ASR_WT:
		ol("__asr.wt");
		break;

	case I_ASR_WI:
		ot("__asr.wi\t");
		out_type(type, data);
		nl();
		break;

	case I_LSR_WT:
		ol("__lsr.wt");
		break;

	case I_LSR_WI:
		ot("__lsr.wi\t");
		out_type(type, data);
		nl();
		break;

	case I_MUL_WT:
		ol("__mul.wt");
		break;

	case I_MUL_WI:
		ot("__mul.wi\t");
		out_type(type, data);
		nl();
		break;

	case I_SDIV_WT:
		ol("__sdiv.wt");
		break;

	case I_SDIV_WI:
		ot("__sdiv.wi\t");
		out_type(type, data);
		nl();
		break;

	case I_UDIV_WT:
		ol("__udiv.wt");
		break;

	case I_UDIV_WI:
		ot("__udiv.wi\t");
		out_type(type, data);
		nl();
		break;

	case I_UDIV_UI:
		ot("__udiv.ui\t");
		out_type(type, data);
		nl();
		break;

	case I_SMOD_WT:
		ol("__smod.wt");
		break;

	case I_SMOD_WI:
		ot("__smod.wi\t");
		out_type(type, data);
		nl();
		break;

	case I_UMOD_WT:
		ol("__umod.wt");
		break;

	case I_UMOD_WI:
		ot("__umod.wi\t");
		out_type(type, data);
		nl();
		break;

	case I_UMOD_UI:
		ot("__umod.ui\t");
		out_type(type, data);
		nl();
		break;

	case I_DOUBLE_WT:
		ol("__double");
		break;

	/* i-codes for 8-bit math with lo-byte of the primary register */

	case X_ADD_UIQ:
		ot("__add.uiq\t");
		out_type(type, data);
		nl();
		break;

	case X_ADD_UMQ:
		ot("__add.umq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_UPQ:
		ot("__add.upq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_USQ:
		ot("__add.usq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_ADD_UATQ:
		ot("__add.uatq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_UAXQ:
		ot("__add.uaxq\t");
		out_addr(type, data);
		nl();
		break;

	case X_SUB_UIQ:
		ot("__sub.uiq\t");
		out_type(type, data);
		nl();
		break;

	case X_SUB_UMQ:
		ot("__sub.umq\t");
		out_addr(type, data);
		nl();
		break;

	case X_SUB_UPQ:
		ot("__sub.upq\t");
		out_addr(type, data);
		nl();
		break;

	case X_SUB_USQ:
		ot("__sub.usq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_SUB_UATQ:
		ot("__sub.uatq\t");
		out_addr(type, data);
		nl();
		break;

	case X_SUB_UAXQ:
		ot("__sub.uaxq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ISUB_UIQ:
		ot("__isub.uiq\t");
		out_type(type, data);
		nl();
		break;

	case X_ISUB_UMQ:
		ot("__isub.umq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ISUB_UPQ:
		ot("__isub.upq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ISUB_USQ:
		ot("__isub.usq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_ISUB_UATQ:
		ot("__isub.uatq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ISUB_UAXQ:
		ot("__isub.uaxq\t");
		out_addr(type, data);
		nl();
		break;

	case X_AND_UIQ:
		ot("__and.uiq\t");
		out_type(type, data);
		nl();
		break;

	case X_AND_UMQ:
		ot("__and.umq\t");
		out_addr(type, data);
		nl();
		break;

	case X_AND_UPQ:
		ot("__and.upq\t");
		out_addr(type, data);
		nl();
		break;

	case X_AND_USQ:
		ot("__and.usq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_AND_UATQ:
		ot("__and.uatq\t");
		out_addr(type, data);
		nl();
		break;

	case X_AND_UAXQ:
		ot("__and.uaxq\t");
		out_addr(type, data);
		nl();
		break;

	case X_EOR_UIQ:
		ot("__eor.uiq\t");
		out_type(type, data);
		nl();
		break;

	case X_EOR_UMQ:
		ot("__eor.umq\t");
		out_addr(type, data);
		nl();
		break;

	case X_EOR_UPQ:
		ot("__eor.upq\t");
		out_addr(type, data);
		nl();
		break;

	case X_EOR_USQ:
		ot("__eor.usq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_EOR_UATQ:
		ot("__eor.uatq\t");
		out_addr(type, data);
		nl();
		break;

	case X_EOR_UAXQ:
		ot("__eor.uaxq\t");
		out_addr(type, data);
		nl();
		break;

	case X_OR_UIQ:
		ot("__or.uiq\t");
		out_type(type, data);
		nl();
		break;

	case X_OR_UMQ:
		ot("__or.umq\t");
		out_addr(type, data);
		nl();
		break;

	case X_OR_UPQ:
		ot("__or.upq\t");
		out_addr(type, data);
		nl();
		break;

	case X_OR_USQ:
		ot("__or.usq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_OR_UATQ:
		ot("__or.uatq\t");
		out_addr(type, data);
		nl();
		break;

	case X_OR_UAXQ:
		ot("__or.uaxq\t");
		out_addr(type, data);
		nl();
		break;

	case I_ASL_UIQ:
		ot("__asl.uiq\t");
		out_type(type, data);
		nl();
		break;

	case I_LSR_UIQ:
		ot("__lsr.uiq\t");
		out_type(type, data);
		nl();
		break;

	case I_MUL_UIQ:
		ot("__mul.uiq\t");
		out_type(type, data);
		nl();
		break;

	/* i-codes for modifying a variable with "+=", "-=", "&=", "^=", "|=" */

	case X_ADD_ST_WMQ:
		ot("__add_st.wmq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_ST_UMQ:
		ot("__add_st.umq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_ST_WPQ:
		ot("__add_st.wpq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_ST_UPQ:
		ot("__add_st.upq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_ST_WSQ:
		ot("__add_st.wsq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_ADD_ST_USQ:
		ot("__add_st.usq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_ADD_ST_WATQ:
		ot("__add_st.watq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_ST_UATQ:
		ot("__add_st.uatq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_ST_WAXQ:
		ot("__add_st.waxq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_ST_UAXQ:
		ot("__add_st.uaxq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ISUB_ST_WMQ:
		ot("__isub_st.wmq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ISUB_ST_UMQ:
		ot("__isub_st.umq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ISUB_ST_WPQ:
		ot("__isub_st.wpq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ISUB_ST_UPQ:
		ot("__isub_st.upq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ISUB_ST_WSQ:
		ot("__isub_st.wsq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_ISUB_ST_USQ:
		ot("__isub_st.usq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_ISUB_ST_WATQ:
		ot("__isub_st.watq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ISUB_ST_UATQ:
		ot("__isub_st.uatq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ISUB_ST_WAXQ:
		ot("__isub_st.waxq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ISUB_ST_UAXQ:
		ot("__isub_st.uaxq\t");
		out_addr(type, data);
		nl();
		break;

	case X_AND_ST_WMQ:
		ot("__and_st.wmq\t");
		out_addr(type, data);
		nl();
		break;

	case X_AND_ST_UMQ:
		ot("__and_st.umq\t");
		out_addr(type, data);
		nl();
		break;

	case X_AND_ST_WPQ:
		ot("__and_st.wpq\t");
		out_addr(type, data);
		nl();
		break;

	case X_AND_ST_UPQ:
		ot("__and_st.upq\t");
		out_addr(type, data);
		nl();
		break;

	case X_AND_ST_WSQ:
		ot("__and_st.wsq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_AND_ST_USQ:
		ot("__and_st.usq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_AND_ST_WATQ:
		ot("__and_st.watq\t");
		out_addr(type, data);
		nl();
		break;

	case X_AND_ST_UATQ:
		ot("__and_st.uatq\t");
		out_addr(type, data);
		nl();
		break;

	case X_AND_ST_WAXQ:
		ot("__and_st.waxq\t");
		out_addr(type, data);
		nl();
		break;

	case X_AND_ST_UAXQ:
		ot("__and_st.uaxq\t");
		out_addr(type, data);
		nl();
		break;

	case X_EOR_ST_WMQ:
		ot("__eor_st.wmq\t");
		out_addr(type, data);
		nl();
		break;

	case X_EOR_ST_UMQ:
		ot("__eor_st.umq\t");
		out_addr(type, data);
		nl();
		break;

	case X_EOR_ST_WPQ:
		ot("__eor_st.wpq\t");
		out_addr(type, data);
		nl();
		break;

	case X_EOR_ST_UPQ:
		ot("__eor_st.upq\t");
		out_addr(type, data);
		nl();
		break;

	case X_EOR_ST_WSQ:
		ot("__eor_st.wsq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_EOR_ST_USQ:
		ot("__eor_st.usq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_EOR_ST_WATQ:
		ot("__eor_st.watq\t");
		out_addr(type, data);
		nl();
		break;

	case X_EOR_ST_UATQ:
		ot("__eor_st.uatq\t");
		out_addr(type, data);
		nl();
		break;

	case X_EOR_ST_WAXQ:
		ot("__eor_st.waxq\t");
		out_addr(type, data);
		nl();
		break;

	case X_EOR_ST_UAXQ:
		ot("__eor_st.uaxq\t");
		out_addr(type, data);
		nl();
		break;

	case X_OR_ST_WMQ:
		ot("__or_st.wmq\t");
		out_addr(type, data);
		nl();
		break;

	case X_OR_ST_UMQ:
		ot("__or_st.umq\t");
		out_addr(type, data);
		nl();
		break;

	case X_OR_ST_WPQ:
		ot("__or_st.wpq\t");
		out_addr(type, data);
		nl();
		break;

	case X_OR_ST_UPQ:
		ot("__or_st.upq\t");
		out_addr(type, data);
		nl();
		break;

	case X_OR_ST_WSQ:
		ot("__or_st.wsq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_OR_ST_USQ:
		ot("__or_st.usq\t");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_OR_ST_WATQ:
		ot("__or_st.watq\t");
		out_addr(type, data);
		nl();
		break;

	case X_OR_ST_UATQ:
		ot("__or_st.uatq\t");
		out_addr(type, data);
		nl();
		break;

	case X_OR_ST_WAXQ:
		ot("__or_st.waxq\t");
		out_addr(type, data);
		nl();
		break;

	case X_OR_ST_UAXQ:
		ot("__or_st.uaxq\t");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_ST_WMIQ:
		ot("__add_st.wmiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_type(type, data);
		nl();
		break;

	case X_ADD_ST_UMIQ:
		ot("__add_st.umiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_type(type, data);
		nl();
		break;

	case X_ADD_ST_WPIQ:
		ot("__add_st.wpiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_ST_UPIQ:
		ot("__add_st.upiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_ST_WSIQ:
		ot("__add_st.wsiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_ADD_ST_USIQ:
		ot("__add_st.usiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_ADD_ST_WATIQ:
		ot("__add_st.watiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_ST_UATIQ:
		ot("__add_st.uatiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_ST_WAXIQ:
		ot("__add_st.waxiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_addr(type, data);
		nl();
		break;

	case X_ADD_ST_UAXIQ:
		ot("__add_st.uaxiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_addr(type, data);
		nl();
		break;

	case X_SUB_ST_WMIQ:
		ot("__sub_st.wmiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_type(type, data);
		nl();
		break;

	case X_SUB_ST_UMIQ:
		ot("__sub_st.umiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_type(type, data);
		nl();
		break;

	case X_SUB_ST_WPIQ:
		ot("__sub_st.wpiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_addr(type, data);
		nl();
		break;

	case X_SUB_ST_UPIQ:
		ot("__sub_st.upiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_addr(type, data);
		nl();
		break;

	case X_SUB_ST_WSIQ:
		ot("__sub_st.wsiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_SUB_ST_USIQ:
		ot("__sub_st.usiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		outdec((int)data);
		outlocal(tmp->sym);
		nl();
		break;

	case X_SUB_ST_WATIQ:
		ot("__sub_st.watiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_addr(type, data);
		nl();
		break;

	case X_SUB_ST_UATIQ:
		ot("__sub_st.uatiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_addr(type, data);
		nl();
		break;

	case X_SUB_ST_WAXIQ:
		ot("__sub_st.waxiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_addr(type, data);
		nl();
		break;

	case X_SUB_ST_UAXIQ:
		ot("__sub_st.uaxiq\t");
		out_type(imm_type, imm_data);
		outstr(", ");
		out_addr(type, data);
		nl();
		break;

	default:
		gen_asm(tmp);
		break;
	}

	/* mark the instruction as invalid */
	tmp->ins_code = I_RETIRED;
}

/* ----
 * gen_asm()
 * ----
 * generate optimizer asm code
 *
 */
void gen_asm (INS *inst)
{
//	int type = inst->ins_type;
//	intptr_t data = inst->ins_data;

	/* i-codes for 32-bit longs */

	switch (inst->ins_code) {

	case X_LDD_I:
		ot("__ldd_i\t\t");
		outdec((int)inst->ins_data);
		outstr(", ");
		prefix();
		outstr(inst->arg[0]);
		outstr(", ");
		prefix();
		outstr(inst->arg[1]);
		nl();
		break;

	case X_LDD_W:
		ot("__ldd_w\t\t");
		outsymbol((SYMBOL *)inst->ins_data);
		outstr(", ");
		prefix();
		outstr(inst->arg[0]);
		outstr(", ");
		prefix();
		outstr(inst->arg[1]);
		nl();
		break;

	case X_LDD_B:
		ot("__ldd_b\t\t");
		outsymbol((SYMBOL *)inst->ins_data);
		outstr(", ");
		prefix();
		outstr(inst->arg[0]);
		outstr(", ");
		prefix();
		outstr(inst->arg[1]);
		nl();
		break;

	case X_LDD_S_W:
		ot("__ldd_s_w\t");
		outdec((int)inst->ins_data);
		outstr(", ");
		prefix();
		outstr(inst->arg[0]);
		outstr(", ");
		prefix();
		outstr(inst->arg[1]);
		nl();
		break;

	case X_LDD_S_B:
		ot("__ldd_s_b\t");
		outdec((int)inst->ins_data);
		outstr(", ");
		prefix();
		outstr(inst->arg[0]);
		outstr(", ");
		prefix();
		outstr(inst->arg[1]);
		nl();
		break;

	default:
		error("internal error: invalid instruction");
		break;
	}
}
